# LIBRARY

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics

# DATA

In [2]:
df1 = pd.read_csv('decisiontree.csv')

In [3]:
df1.describe()

              ID     bangku
count  40.000000  40.000000
mean   20.500000   5.300000
std    11.690452   2.015326
min     1.000000   2.000000
25%    10.750000   4.000000
50%    20.500000   4.500000
75%    30.250000   8.000000
max    40.000000   8.000000

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         40 non-null     int64
 1   mesin      40 non-null     object
 2   bangku     40 non-null     int64
 3   penggerak  40 non-null     object
 4   label      40 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.7+ KB

# PRE-PROCESSING DATA

## DATA TRANSFORMATION

In [5]:
encoding = {
    "mesin": {"bensin": 0, "diesel":1},
    "penggerak": {"depan":0, "belakang":1}
}
df1.replace(encoding, inplace=True)

In [6]:
df1

    ID  mesin  bangku  penggerak    label
0    1      0       4          0    sedan
1    2      0       2          0    sedan
2    3      0       8          1  minibus
3    4      1       6          0  minibus
4    5      0       5          1  minibus
5    6      1       8          1  minibus
6    7      1       8          1  minibus
7    8      0       4          0    sedan
8    9      1       7          1  minibus
9   10      0       4          0    sedan
10  11      0       2          0    sedan
11  12      1       6          1  minibus
12  13      1       8          0  minibus
13  14      0       4          0    sedan
14  15      1       2          0    sedan
15  16      0       4          0    sedan
16  17      0       8          1  minibus
17  18      0       4          0    sedan
18  19      1       8          1  minibus
19  20      1       8          1  minibus
20  21      0       4          0    sedan
21  22      0       4          0  minibus
22  23      1       8          1  minibus
23  24      0       4          0    sedan
24  25      0       5          1  minibus
25  26      0       4          0  minibus
26  27      1       8          1  minibus
27  28      0       4          0    sedan
28  29      0       7          1  minibus
29  30      0       4          0    sedan
30  31      0       4          0    sedan
31  32      0       2          0    sedan
32  33      0       8          1  minibus
33  34      1       6          0  minibus
34  35      0       5          1  minibus
35  36      1       8          1  minibus
36  37      1       4          1  minibus
37  38      0       4          0    sedan
38  39      1       5          1  minibus
39  40      0       4          0    sedan

Karena sampelnya yang sangat sedikit, maka langsung modeling

In [7]:
df = df1.copy()

# MODELING

In [8]:
X = df.drop(['label','ID'], axis='columns')
y = df['label']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [10]:
model = tree.DecisionTreeClassifier(criterion='gini', max_depth=5)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [11]:
y_pred = model.predict(X_test)

In [12]:
metrics.accuracy_score(y_test, y_pred)

1.0